"""add transactions

Revision ID: 2dc68b06aba4
Revises: cadb09f37316
Create Date: 2026-08-18 17:08:45.612374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc68b06aba4'
down_revision: Union[str, Sequence[str], None] = 'cadb09f37316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('traded_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('buy', 'sell')", name='ck_transactions_side'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.CheckConstraint('price > 0', name='ck_transactions_price_non_negative'),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_holding_id'), 'transactions', ['holding_id'], unique=False)
    op.create_index(op.f('ix_transactions_traded_on'), 'transactions', ['traded_on'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO transactions (holding_id, side, amount, price, traded_on, created_at)
        SELECT id, 'buy', amount, avg_price, (created_at)::date, created_at
        FROM holdings
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_traded_on'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_holding_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
