"""drop holding aggregates

Revision ID: 994d3ce07b68
Revises: 2dc68b06aba4
Create Date: 2026-08-18 18:54:49.840438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994d3ce07b68'
down_revision: Union[str, Sequence[str], None] = '2dc68b06aba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'amount')
    op.drop_column('holdings', 'avg_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('holdings', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('holdings', sa.Column('avg_price', sa.Float(), nullable=True))

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT holding_id, side, amount, price FROM transactions "
                                "ORDER BY holding_id, traded_on, id"
                                )
                        )
    aggregates: dict[int, tuple[float, float]] = {}
    for holding_id, side, amount, price in rows:
        held, avg = aggregates.get(holding_id, (0.0, 0.0))
        if side == "buy":
            new_held = held + amount
            aggregates[holding_id] = (new_held, (held * avg + amount * price) / new_held)
        else:
            aggregates[holding_id] = (held - amount, avg)

    for holding_id, (amount, avg_price) in aggregates.items():
        conn.execute(
            sa.text("UPDATE holdings SET amount = :amount, avg_price = :avg_price "
                    "WHERE id = :id"
                    ),
            {"amount": amount, "avg_price": avg_price, "id": holding_id}
        )

    op.execute("UPDATE holdings SET amount = 0, avg_price = 0  WHERE amount IS NULL")
    op.alter_column('holdings', 'amount', nullable=False)
    op.alter_column('holdings', 'avg_price', nullable=False)