"""Add key to holdings

Revision ID: cadb09f37316
Revises: eaf81e012054
Create Date: 2026-06-07 17:34:48.620596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadb09f37316'
down_revision: Union[str, Sequence[str], None] = 'eaf81e012054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('key', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('holdings_user_id_symbol_kind_key'), 'holdings', type_='unique')
    op.create_unique_constraint(None, 'holdings', ['user_id', 'key', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdings', type_='unique')
    op.create_unique_constraint(op.f('holdings_user_id_symbol_kind_key'), 'holdings', ['user_id', 'symbol', 'kind'], postgresql_nulls_not_distinct=False)
    op.drop_column('holdings', 'key')
    # ### end Alembic commands ###
