"""add symbol to asset_price_cache

Revision ID: f06fc3bc3053
Revises: f73f688e87bb
Create Date: 2026-05-07 18:28:10.926635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06fc3bc3053'
down_revision: Union[str, Sequence[str], None] = 'f73f688e87bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_price_cache', sa.Column('symbol', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_price_cache', 'symbol')
    # ### end Alembic commands ###
