"""add asset price chache

Revision ID: f73f688e87bb
Revises: 399155dc2118
Create Date: 2026-05-07 16:50:02.426389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73f688e87bb'
down_revision: Union[str, Sequence[str], None] = '399155dc2118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'key')
    )
    op.add_column('holdings', sa.Column('kind', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('holdings_user_id_symbol_key'), 'holdings', type_='unique')
    op.create_unique_constraint(None, 'holdings', ['user_id', 'symbol', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdings', type_='unique')
    op.create_unique_constraint(op.f('holdings_user_id_symbol_key'), 'holdings', ['user_id', 'symbol'], postgresql_nulls_not_distinct=False)
    op.drop_column('holdings', 'kind')
    op.drop_table('asset_price_cache')
    # ### end Alembic commands ###
